version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: poc-postgres

    environment:
      POSTGRES_DB: pocdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ..
      dockerfile: Backend/POC.API/POC.API/Dockerfile

    container_name: poc-api

    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=pocdb;Username=postgres;Password=postgres

    depends_on:
      - postgres

    ports:
      - "5000:5000"

  frontend:
    build:
      context: ../frontend

    container_name: poc-frontend

    depends_on:
      - api

    ports:
      - "5173:80"

volumes:
  postgres_data: